# Generated by Django 5.1.5 on 2025-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Daily Unlimited'), (1, 'Scheduled with Repeats'), (2, 'User-Controlled Perpetual')], default=0),
        ),
    ]
