# Generated by Django 5.1.5 on 2025-01-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardfeature',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='board',
            name='serial_number',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
