# Generated by Django 5.1.4 on 2025-01-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_boardfeature_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpublication',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationtype',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationtype',
            name='event',
        ),
        migrations.AddField(
            model_name='boardpublication',
            name='address',
            field=models.FileField(blank=True, null=True, upload_to='publication_files/'),
        ),
        migrations.AddField(
            model_name='boardpublication',
            name='description',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='boardpublication',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='publications_with_event', to='boards.event'),
        ),
        migrations.AddField(
            model_name='boardpublication',
            name='interaction',
            field=models.URLField(blank=True, help_text='e.g., http://example.com', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='boardpublication',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='publications_by_user', to='boards.user'),
        ),
        migrations.AddField(
            model_name='repetition',
            name='current_cycle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repetition',
            name='repetition_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='serial_number',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='boardpublication',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_in_board', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='repetition',
            name='board_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions_for_publication', to='boards.boardpublication'),
        ),
        migrations.AlterField(
            model_name='repetition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='PublicationType',
        ),
    ]
