# Generated by Django 5.1.4 on 2025-01-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_boardpublication_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='address',
            field=models.FileField(default='', upload_to='publication_files/'),
        ),
        migrations.AlterField(
            model_name='boardpublication',
            name='description',
            field=models.CharField(default='', max_length=27),
        ),
        migrations.AlterField(
            model_name='boardpublication',
            name='interaction',
            field=models.URLField(default='', help_text='e.g., http://example.com', max_length=18),
        ),
    ]
