# Generated by Django 5.1.4 on 2025-01-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_board_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_with_event', to='boards.event'),
        ),
    ]
