# Generated by Django 5.1.4 on 2025-01-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_boardpublication_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_by_user', to='boards.user'),
        ),
    ]
