# Generated by Django 5.1.4 on 2025-01-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_boardpublication_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='address',
            field=models.FileField(upload_to='publication_files/'),
        ),
    ]
