# Generated by Django 5.1.4 on 2025-01-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_boardpublication_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpublication',
            name='description',
            field=models.CharField(max_length=27),
        ),
    ]
